[package]
name = "ptarslib"
version = "0.0.0"
authors = ["0x26res <0x26res@gmail.net>"]
edition = "2021"
description = "Fast python conversion from protobuf to arrow using rust"
homepage = "https://github.com/0x26res/ptars"
repository = "https://github.com/0x26res/ptars"
readme = "README.md"
license = "Apache-2.0"

[package.metadata.release]
publish = false # handled by GitHub Actions
push = true

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.0" }
arrow = { version = "50.0.0", features = ["pyarrow"] }
arrow-array = { version = "49.0.0" }
arrow-schema = { version = "49.0.0" }
protobuf = { version = "3.3.0" }

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
